version: "3.9"

services:

  django:
    build: .
    container_name: trackapp
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
    - .:/track
    ports:
    - "8000:8000"
    env_file:
      - ./track/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.6.10-alpine
    container_name: pgtrack
    restart: always
    user: postgres
    volumes:
    - trackdb:/var/lib/postgresql/data/
    env_file:
      - ./track/.env

  redis:
    image: redis:6.0-alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'

  celery:
    restart: always
    build: .
    command: >
      sh -c "celery -A track worker -l info -f output"
    volumes:
      - .:/track
    depends_on:
      - redis
      - db
      - django
    env_file:
      - ./track/.env

  celery-beat:
    build: .
    command: >
      sh -c "celery -A track beat -l info -f output"
    volumes:
    - .:/track
    depends_on:
      - redis
      - db
      - django
    env_file:
      - ./track/.env

volumes:
  trackdb:
