# Generated by Django 3.2 on 2021-11-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StarterGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced', models.ManyToManyField(related_name='guide_adv', to='dashboard.AdvancedGuide')),
                ('intermediate', models.ManyToManyField(related_name='guide_inter', to='dashboard.IntermediateGuide')),
                ('starter', models.ManyToManyField(related_name='guide_starter', to='dashboard.StarterGuide')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='Train     as a/an (Programmer/Accountant/etc)', max_length=255)),
                ('aoc', models.CharField(help_text='simple field description', max_length=255, verbose_name='area of concentration')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_guide', to='dashboard.guide')),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.ManyToManyField(related_name='dashboard_field', to='dashboard.Field')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
