# Generated by Django 3.2 on 2021-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='publication',
            field=models.ManyToManyField(related_name='dashboard_publication', to='publication.Publication'),
        ),
    ]
